### ISSUE TITLE
Example from README doesn't work

### ISSUE THREAD

**Issue by ReveekJ** [AlvifSandana/xorencryption#3]
Hi there! I try to start code from README, but my decrypt result is empty:
```py
from xorencryption import XOREncryption

plain = "this is your plain text"
key = 'boom'
enc = XOREncryption()

enc.set_plaintext(plaintext=plain)
enc.set_key(key=key)

print(enc.encrypt())  # return cipher text
print(enc.decrypt())  # return decrypted text
```
and the output:
```
BM BO

```
the decrypt row is empty
what's wrong?

**Comment by Damianv99** [comment]
You need to set the __ciphertext variable. Its blank and that is why its returning nothing.
Add this after you set the plaintext and key: `enc.set_ciphertext(enc.encrypt())`

Now when you call the decrypt function it should return something

**Comment by ReveekJ** [comment]
Thanks it's really work
